### ISSUE TITLE
Error occurs when the ts parser for the corresponding language is not installed

### ISSUE THREAD

**Issue by BBboy01** [aaronik/treewalker.nvim#12]
Maybe we can early stop running if there is no corresponding ts parser

`vim.bo.ft`: `ocaml`

![CleanShot 2024-12-20 at 14 18 15@2x](https://github.com/user-attachments/assets/b44c500c-9471-4613-9286-cbdd1eb1bc8d)

**Comment by aaronik** [comment]
Oh snap - good catch. Got any fixes?
