### ISSUE TITLE
<Left><Right> should take you to back to where you started.

### ISSUE THREAD

**Issue by AlexJWayne** [aaronik/treewalker.nvim#14]
This is just an idea, I'll let you decide if it's a good one.

I think that lefts should internally bookmark where you were in case you wanted to go back.

For instance:

```js
function foo() {
  const a = true
  const b = false
//^ cursor
}

// <Treewalker Left>
// <Treewalker Right>

// expected
function foo() {
  const a = true
  const b = false
//^
}

// actual current result
function foo() {
  const a = true
//^
  const b = false
}
```

This would be handy to peek at a functions args real quick, then go back to where you were just by doing the opposite of how you got there.

If you `Treewalker Up/Down` then I think it would make sense to clear this internal bookmark.

This similar to how the cursor it's column even when moving to a shorter row:

```
short
loooooong
         ^


<UpArrow>


short
     ^
loooooong


<DownArrow>


short
loooooong
         ^
```

Here the cursor remembers where it was even when the line its on is shorter. But if you did up/left/down, then it forgets because of the left.

I'm not sure everyone would want this, so maybe it's an option?

**Comment by aaronik** [comment]
A big part of this plugin's design was to be stateless, so I'm not going to implement something like this explicitly. Plus the intended behavior of Right precludes Left being its exact opposite.

However! The plugin does add every movement to the jump list 🙂 so your use case actually is already taken care of, you can jump in to preview a function or whatever, then just press Ctrl-o to back out!
