### ISSUE TITLE
Errors raised- "attempt to index a boolean value"

### ISSUE THREAD

**Issue by mnussbaum** [aaronik/treewalker.nvim#17]
Hi there, I've just installed treewalker and configured it per the README, but when I attempt to trigger any of the shortcuts I get the following error:

```
Error executing Lua callback: ...m/site/pack/packer/start/treewalker.nvim/plugin/init.lua:17: attempt to index a boolean value
stack traceback:
        ...m/site/pack/packer/start/treewalker.nvim/plugin/init.lua:17: in function <...m/site/pack/packer/start/treewalker.nvim/plugin/init.lua:16>
        ...m/site/pack/packer/start/treewalker.nvim/plugin/init.lua:45: in function <...m/site/pack/packer/start/treewalker.nvim/plugin/init.lua:42>
```

I've seen this in both Python and Lua files, and I have treesitter available for both languages. Let me know if there's any info I can provide to help debug!

**Comment by aaronik** [comment]
Oh hmm, that's concerning -- can you provide your config please?

**Comment by aaronik** [comment]
Also, what's the output of `:lua print(jit.version)`?

**Comment by mnussbaum** [comment]
Sure thing, config is:

```lua
vim.keymap.set({ "n", "v" }, "<C-k>", "<cmd>Treewalker Up<cr>", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C-j>", "<cmd>Treewalker Down<cr>", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C-l>", "<cmd>Treewalker Right<cr>", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C-h>", "<cmd>Treewalker Left<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-S-j>", "<cmd>Treewalker SwapDown<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-S-k>", "<cmd>Treewalker SwapUp<cr>", { noremap = true, silent = true })
```

I've installed it with Packer without any special configuration

**Comment by aaronik** [comment]
Those are the bindings (cool to see the defaults are working for you!) - what I'm after is your packer config. So it should start with a `use` command

**Comment by mnussbaum** [comment]
Ah gotcha! My packer config is split into two files, first file is:

```lua
vim.cmd([[packadd packer.nvim]])

return require("packer").startup(function(use)
    for _, plugin in ipairs(require("plugins")) do
        use(plugin)
    end
end)
```

And then in a `plugins.lua` file that is `require`d above I have:

```lua
return {
  {
    "wbthomason/packer.nvim",
  },
  {
    "preservim/vimux",
  },
  {
    "itchyny/lightline.vim",
  },
  {
    "janko-m/vim-test",
  },
  {
    "jlanzarotta/bufexplorer",
  },
  {
    "liuchengxu/vista.vim",
  },
  {
    "Matt-Deacalion/vim-systemd-syntax",
  },
  {
    "m-pilia/vim-ccls",
  },
  {
    "mhinz/vim-startify",
  },
  {
    "pearofducks/ansible-vim",
  },
  {
    "ryanoasis/vim-devicons",
  },
  {
    "scrooloose/nerdtree",
  },
  {
    "Shougo/context_filetype.vim",
  },
  {
    "tpope/vim-fugitive",
  },
  {
    "terrortylor/nvim-comment",
  },
  {
    "farmergreg/vim-lastplace",
  },
  {
    "nvim-treesitter/nvim-treesitter",
    run = "function() require('nvim-treesitter.install').update({ with_sync = true }) end",
  },
  {
    "neovim/nvim-lspconfig",
  },
  {
    "rcarriga/nvim-notify",
  },
  {
    "L3MON4D3/LuaSnip",
  },
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  {
    "RRethy/nvim-treesitter-textsubjects",
  },
  {
    "stevearc/dressing.nvim",
  },
  {
    "hrsh7th/cmp-nvim-lsp",
  },
  {
    "hrsh7th/cmp-buffer",
  },
  {
    "hrsh7th/cmp-path",
  },
  {
    "hrsh7th/cmp-cmdline",
  },
  {
    "hrsh7th/cmp-emoji",
  },
  {
    "hrsh7th/nvim-cmp",
  },
  {
    "RRethy/nvim-base16",
  },
  {
    "stevearc/conform.nvim",
  },
  {
    "cshuaimin/ssr.nvim",
  },
  {
    "aaronik/treewalker.nvim",
  },
  {
    "nvim-telescope/telescope.nvim",
    branch = "0.1.x",
    requires = "nvim-lua/plenary.nvim",
  },
  {
    "nvim-telescope/telescope-fzf-native.nvim",
    run = "make",
  },
}
```

**Comment by aaronik** [comment]
Hmm I've never used packer (went straight from `vim-plug` to `lazy`), and I'm having trouble making this work. 

I visited [the packer docs](https://github.com/wbthomason/packer.nvim?tab=readme-ov-file#bootstrapping), and used that little `ensure_packer` command - but the plugins don't seem to be appearing. I can confirm they are getting into the `use` directive. I'm not sure how it's supposed to look with packer, all I know is none of the plugins seem to be registering (none of their globally set commands are available).

Would you mind providing a minimal `init.lua` file that ends up still suffering from this issue? One that I can copy/paste into my own init.lua file to easily reproduce the issue you're seeing?

**Comment by aaronik** [comment]
Haven't heard from you for a while on this one so I'm going to close it out. But please re-open it if it's still causing you issues! I definitely want to get to the bottom of this if it's affecting anyone else, too.
