### ISSUE TITLE
Make highlight duration configurable

### ISSUE THREAD

**Issue by ccjmne** [aaronik/treewalker.nvim#5]
Hi,
Thank you for this excellent plug-in!

I like the highlighting, but would want it a bit snappier.
I believe that a nice and easy addition would be to have the highlight duration be configurable.

I think we may not really need to have another property in the current options either, but possibly simply have the `highlight` be a `boolean | integer`, where:
- `nil`, `false` and `0` would disable the highlighting,
- `true` would trigger it for some default duration (let's go with `250ms`, which you've currently set up), and
- any numeric value (other than `0`) would enable highlighting for a duration corresponding to that value.

What do you think?

I've got a PR coming as well, with some implementation.

Cheers!

**Comment by aaronik** [comment]
Hey if you've come here looking for this configurability, please thumbs up the issue, thanks!
