### ISSUE TITLE
Highlight on jump doesn't quite match expectations consistently

### ISSUE THREAD

**Issue by ccjmne** [aaronik/treewalker.nvim#8]
There's some inconsistency in the way the jumps are highlighted.

Here's a recording that illustrates the issue:
[![asciicast](https://asciinema.org/a/RRCAfgO6FXf9DI1ZRjLCRpL4F.svg)](https://asciinema.org/a/RRCAfgO6FXf9DI1ZRjLCRpL4F)

You can see in this example that by jumping Right or Up and Down, it's not always the "outermost" valid node (at the corresponding location) that gets highlighted.

I suspect that we might get away with selecting the earliest ancestor that's still starting at the same row and column.
Actually, just hang on a second, I'll whip out a Pull Request :)

**Comment by aaronik** [comment]
Closed in https://github.com/aaronik/treewalker.nvim/pull/9
